#Create KeyStore
#- name: Check that APM Server keystore exists
#  stat:
#    path: "/usr/share/apm-server/bin/data/apm-server.keystore"
#  register: keystore_exists
#  become: true
#
#- name: Create APM Server keystore
#  become: true
#  shell: "{{ apm_server_home }}/bin/apm-server keystore create -c /etc/apm-server/apm-server.yml "
#  when:  not keystore_exists.stat.exists
#  ignore_errors: true

- name: Add Elasticsearch Output User to Keystore
  become: true
  shell: "echo {{ es_output_user }}| {{ apm_server_home }}/bin/apm-server keystore add ES_USER --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: es_output_user and es_enable_keystore

- name: Print the gateway for each host when defined
  ansible.builtin.debug:
    msg:  "ES Output User--{{ es_output_user }}--"
  when: es_output_user and es_enable_keystore


- name: Add Elasticsearch Output Password to Keystore
  become: true
  shell: "echo {{ es_output_pass }}| {{ apm_server_home }}/bin/apm-server keystore add ES_PASS --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: es_output_pass and es_enable_keystore

- name: Add Kibana User to Keystore
  become: true
  shell: "echo {{ apm_kibana_user }}| {{ apm_server_home }}/bin/apm-server keystore add APM_KIBANA_USER --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: apm_kibana_user and es_enable_keystore

- name: Add Kibana Password to Keystore
  become: true
  shell: "echo {{ apm_kibana_pass }}| {{ apm_server_home }}/bin/apm-server keystore add APM_KIBANA_PASS --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: apm_kibana_pass and es_enable_keystore


- name: Add Elasticsearch Monitoring User to Keystore
  become: true
  shell: "echo {{ es_mon_user }}| {{ apm_server_home }}/bin/apm-server keystore add ES_MON_USER --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: es_mon_enable and es_mon_user and es_enable_keystore

- name: Add Elasticsearch Monitoring Password to Keystore
  become: true
  shell: "echo {{ es_mon_pass }}| {{ apm_server_home }}/bin/apm-server keystore add ES_MON_PASS --stdin --force -c /etc/apm-server/apm-server.yml --path.data {{path_data}}"
  when: es_mon_enable and es_mon_pass and es_enable_keystore

- name: Change file ownership, group and permissions of Keystore and meta.json
  ansible.builtin.file:
    path: "{{path_data}}/{{item}}"
    owner: "{{es_user}}"
    group: "{{ es_group}}"
    mode: "0600"
  with_items:
    - apm-server.keystore
    - meta.json
  become: true