---
# Task SSL

- name: Ensure certificate directory exists
  become: yes
  file:
    dest: "{{ es_ssl_certificate_path }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "750"

- name: Upload Elasticsearch CA Certificate
  become: yes
  copy:
    src: "{{ es_output_ssl_ca }}"
    dest: "{{ es_ssl_certificate_path }}/{{ es_output_ssl_ca | basename }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "640"
  when: es_output_ssl_ca and es_output_ssl_enabled
  notify: restart apm-server
  register: copy_es_cafile
