---
- name: RedHat - Import Elasticsearch PGP key
  ansible.builtin.rpm_key:
    state: present
    key: "{{es_repo_base}}/GPG-KEY-elasticsearch"

- name: RedHat - Install Elastic APM Server from url
  become: yes
  yum: name={% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}-x86_64.rpm{% endif %} state=present
  when: not es_use_repository
  register: elastic_apm_server_install_from_package
  notify: restart apm-server
