---
# tasks file for ansible-role-elastic-apm-server
- name: include elastic-apm-server.yml
  include: elastic-apm-server.yml
  tags:
    - install

- name: include elastic-apm-server-config.yml
  include: elastic-apm-server-config.yml
  tags:
    - config

- name: include elastic-apm-server-keystore.yml
  include: elastic-apm-server-keystore.yml
  tags:
    - config

- name: include elastic-apm-server-ssl.yml
  include: elastic-apm-server-ssl.yml
  when: es_enable_ssl
  tags:
    - config
